[project]
name = "underthesea"
version = "8.0.0a0"
description = "Vietnamese NLP Toolkit"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flake8>=7.3.0",
    'Click>=6.0',
    'python-crfsuite>=0.9.6',
    'nltk==3.8',
    'tqdm',
    'requests',
    'joblib',
    'scikit-learn==1.6.0',
    'PyYAML',
    'underthesea_core==1.0.5'
]
